version: "3"

services:
  status-bots:
    build: .
    environment:
      PRICE_TICKER_TOKEN: "${PRICE_TICKER_TOKEN}"
      LOCKED_TICKER_TOKEN: "${LOCKED_TICKER_TOKEN}"
      VOTES_TICKER_TOKEN: "${VOTES_TICKER_TOKEN}"
    restart: on-failure
